### ISSUE TITLE
Problem 1 (Handled by Anusha R)

### ISSUE THREAD

**Issue by muhammedjassim** [muhammedjassim/PBSR-Assignments#2]
I could figure the solutions for the first 3 questions of Problem 1. But from the 4th question, I've found some inconsistencies in the question. Furthermore, the 5th question asks to use Poisson distribution. But how is that possible with different values of mean and variance?

**Comment by ranusha27** [comment]
Poisson distribution cannot be used, as the values of mean and variance are different. Maybe that is a mistake in the question.
