### ISSUE TITLE
Problem 3 (Handled by Muhammed Jassim)

### ISSUE THREAD

**Issue by ranusha27** [muhammedjassim/PBSR-Assignments#3]
How do you choose between the given models based on AIC value? How is AIC calculated?

**Comment by muhammedjassim** [comment]
The model with the lower AIC value is considered to be the model with the best fit.
AIC is a mathematical method for evaluating how well a model fits the data it was generated from. It is calculated as:
`2K – 2(log-likelihood)` Where `K` is the number of parameters.
