### ISSUE TITLE
Problem 4 (Handled by Narendran Ramakrishnan)

### ISSUE THREAD

**Issue by muhammedjassim** [muhammedjassim/PBSR-Assignments#8]
I have been trying to fit the model in part C, but it keeps throwing an error. The error message is saying `unable to evaluate fn at initial points`. Could you please look into this?

**Comment by narendranr0112** [comment]
I saw that in the data provided, `claims` takes the value 0  at a certain point. As  the domain of log normal is (0,∞), the code is throwing an error when we provide  the value 0 for log normal. Lets try removing that and running the code again.
